name = "grich-astro"
main = "worker.js"
account_id = "c70f291b77fbc02a6f2090ebe4abdd44"
compatibility_date = "2026-01-13"

# Workers Sites 配置（SSR方案）
[site]
bucket = "./dist"

# 环境变量
[vars]
PUBLIC_SUPABASE_URL = "https://rdlmumybuwveaaeceohj.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_aPXWTauRxJ88A88mwLDoPQ_puVi7PZj"
