-- Bulk Seed Brands (Engine A) 
INSERT INTO keywords (brand_name, status, source_url) VALUES 
('Nike', 'active', 'bulk_import'),
('Adidas', 'active', 'bulk_import'),
('Puma', 'active', 'bulk_import'),
('Under Armour', 'active', 'bulk_import'),
('New Balance', 'active', 'bulk_import'),
('Reebok', 'active', 'bulk_import'),
('Asics', 'active', 'bulk_import'),
('Skechers', 'active', 'bulk_import'),
('Converse', 'active', 'bulk_import'),
('Vans', 'active', 'bulk_import'),
('Apple', 'active', 'bulk_import'),
('Samsung', 'active', 'bulk_import'),
('Huawei', 'active', 'bulk_import'),
('Xiaomi', 'active', 'bulk_import'),
('Oppo', 'active', 'bulk_import'),
('Vivo', 'active', 'bulk_import'),
('OnePlus', 'active', 'bulk_import'),
('Google', 'active', 'bulk_import'),
('Microsoft', 'active', 'bulk_import'),
('Sony', 'active', 'bulk_import'),
('Louis Vuitton', 'active', 'bulk_import'),
('Gucci', 'active', 'bulk_import'),
('Chanel', 'active', 'bulk_import'),
('Hermès', 'active', 'bulk_import'),
('Prada', 'active', 'bulk_import'),
('Dior', 'active', 'bulk_import'),
('Burberry', 'active', 'bulk_import'),
('Fendi', 'active', 'bulk_import'),
('Versace', 'active', 'bulk_import'),
('Balenciaga', 'active', 'bulk_import'),
('Rolex', 'active', 'bulk_import'),
('Omega', 'active', 'bulk_import'),
('Cartier', 'active', 'bulk_import'),
('Patek Philippe', 'active', 'bulk_import'),
('Audemars Piguet', 'active', 'bulk_import'),
('TAG Heuer', 'active', 'bulk_import'),
('Breitling', 'active', 'bulk_import'),
('IWC', 'active', 'bulk_import'),
('Panerai', 'active', 'bulk_import'),
('Hublot', 'active', 'bulk_import'),
('Ray-Ban', 'active', 'bulk_import'),
('Oakley', 'active', 'bulk_import'),
('Prada Eyewear', 'active', 'bulk_import'),
('Gucci Eyewear', 'active', 'bulk_import'),
('Versace Eyewear', 'active', 'bulk_import'),
('Tom Ford', 'active', 'bulk_import'),
('Persol', 'active', 'bulk_import'),
('Maui Jim', 'active', 'bulk_import'),
('Costa Del Mar', 'active', 'bulk_import'),
('Warby Parker', 'active', 'bulk_import'),
('The North Face', 'active', 'bulk_import'),
('Patagonia', 'active', 'bulk_import'),
('Columbia', 'active', 'bulk_import'),
('Arc''teryx', 'active', 'bulk_import'),
('Marmot', 'active', 'bulk_import'),
('Mammut', 'active', 'bulk_import'),
('Salomon', 'active', 'bulk_import'),
('Merrell', 'active', 'bulk_import'),
('Timberland', 'active', 'bulk_import'),
('Keen', 'active', 'bulk_import'),
('Lululemon', 'active', 'bulk_import'),
('Athleta', 'active', 'bulk_import'),
('Gymshark', 'active', 'bulk_import'),
('Alo Yoga', 'active', 'bulk_import'),
('Fabletics', 'active', 'bulk_import'),
('Outdoor Voices', 'active', 'bulk_import'),
('Sweaty Betty', 'active', 'bulk_import'),
('Vuori', 'active', 'bulk_import'),
('Rhone', 'active', 'bulk_import'),
('Ten Thousand', 'active', 'bulk_import'),
('Zara', 'active', 'bulk_import'),
('H&M', 'active', 'bulk_import'),
('Uniqlo', 'active', 'bulk_import'),
('Gap', 'active', 'bulk_import'),
('Forever 21', 'active', 'bulk_import'),
('Mango', 'active', 'bulk_import'),
('Topshop', 'active', 'bulk_import'),
('Massimo Dutti', 'active', 'bulk_import'),
('Bershka', 'active', 'bulk_import'),
('Pull&Bear', 'active', 'bulk_import'),
('Coach', 'active', 'bulk_import'),
('Michael Kors', 'active', 'bulk_import'),
('Kate Spade', 'active', 'bulk_import'),
('Tory Burch', 'active', 'bulk_import'),
('Longchamp', 'active', 'bulk_import'),
('Furla', 'active', 'bulk_import'),
('MCM', 'active', 'bulk_import'),
('Fossil', 'active', 'bulk_import'),
('Dooney & Bourke', 'active', 'bulk_import'),
('Rebecca Minkoff', 'active', 'bulk_import'),
('Levi''s', 'active', 'bulk_import'),
('Wrangler', 'active', 'bulk_import'),
('Lee', 'active', 'bulk_import'),
('Diesel', 'active', 'bulk_import'),
('G-Star RAW', 'active', 'bulk_import'),
('True Religion', 'active', 'bulk_import'),
('7 For All Mankind', 'active', 'bulk_import'),
('AG Jeans', 'active', 'bulk_import'),
('Citizens of Humanity', 'active', 'bulk_import'),
('Paige', 'active', 'bulk_import'),
('Calvin Klein', 'active', 'bulk_import'),
('Tommy Hilfiger', 'active', 'bulk_import'),
('Ralph Lauren', 'active', 'bulk_import'),
('Lacoste', 'active', 'bulk_import'),
('Hugo Boss', 'active', 'bulk_import'),
('Armani', 'active', 'bulk_import'),
('Versace Jeans', 'active', 'bulk_import'),
('Diesel Jeans', 'active', 'bulk_import'),
('Guess', 'active', 'bulk_import'),
('Abercrombie & Fitch', 'active', 'bulk_import'),
('Victoria''s Secret', 'active', 'bulk_import'),
('La Perla', 'active', 'bulk_import'),
('Agent Provocateur', 'active', 'bulk_import'),
('Calvin Klein Underwear', 'active', 'bulk_import'),
('Tommy John', 'active', 'bulk_import'),
('MeUndies', 'active', 'bulk_import'),
('ThirdLove', 'active', 'bulk_import'),
('Savage X Fenty', 'active', 'bulk_import'),
('Aerie', 'active', 'bulk_import'),
('Pink', 'active', 'bulk_import'),
('Dyson', 'active', 'bulk_import'),
('Shark', 'active', 'bulk_import'),
('iRobot', 'active', 'bulk_import'),
('Bissell', 'active', 'bulk_import'),
('Hoover', 'active', 'bulk_import'),
('Electrolux', 'active', 'bulk_import'),
('Miele', 'active', 'bulk_import'),
('Bosch', 'active', 'bulk_import'),
('KitchenAid', 'active', 'bulk_import'),
('Cuisinart', 'active', 'bulk_import'),
('GoPro', 'active', 'bulk_import'),
('DJI', 'active', 'bulk_import'),
('Canon', 'active', 'bulk_import'),
('Nikon', 'active', 'bulk_import'),
('Fujifilm', 'active', 'bulk_import'),
('Olympus', 'active', 'bulk_import'),
('Panasonic', 'active', 'bulk_import'),
('Leica', 'active', 'bulk_import'),
('Hasselblad', 'active', 'bulk_import'),
('Phase One', 'active', 'bulk_import'),
('Bose', 'active', 'bulk_import'),
('JBL', 'active', 'bulk_import'),
('Harman Kardon', 'active', 'bulk_import'),
('Bang & Olufsen', 'active', 'bulk_import'),
('Sonos', 'active', 'bulk_import'),
('Beats', 'active', 'bulk_import'),
('Sennheiser', 'active', 'bulk_import'),
('Audio-Technica', 'active', 'bulk_import'),
('Shure', 'active', 'bulk_import'),
('AKG', 'active', 'bulk_import'),
('Nintendo', 'active', 'bulk_import'),
('PlayStation', 'active', 'bulk_import'),
('Xbox', 'active', 'bulk_import'),
('Razer', 'active', 'bulk_import'),
('Logitech', 'active', 'bulk_import'),
('Corsair', 'active', 'bulk_import'),
('SteelSeries', 'active', 'bulk_import'),
('HyperX', 'active', 'bulk_import'),
('Alienware', 'active', 'bulk_import'),
('ASUS ROG', 'active', 'bulk_import'),
('Yeti', 'active', 'bulk_import'),
('Hydro Flask', 'active', 'bulk_import'),
('S''well', 'active', 'bulk_import'),
('Contigo', 'active', 'bulk_import'),
('CamelBak', 'active', 'bulk_import'),
('Klean Kanteen', 'active', 'bulk_import'),
('Thermos', 'active', 'bulk_import'),
('Stanley', 'active', 'bulk_import'),
('RTIC', 'active', 'bulk_import'),
('Nalgene', 'active', 'bulk_import'),
('Fitbit', 'active', 'bulk_import'),
('Garmin', 'active', 'bulk_import'),
('Polar', 'active', 'bulk_import'),
('Suunto', 'active', 'bulk_import'),
('Wahoo', 'active', 'bulk_import'),
('Coros', 'active', 'bulk_import'),
('Amazfit', 'active', 'bulk_import'),
('Withings', 'active', 'bulk_import'),
('Oura', 'active', 'bulk_import'),
('Whoop', 'active', 'bulk_import'),
('Crocs', 'active', 'bulk_import'),
('Birkenstock', 'active', 'bulk_import'),
('UGG', 'active', 'bulk_import'),
('Dr. Martens', 'active', 'bulk_import'),
('Clarks', 'active', 'bulk_import'),
('Ecco', 'active', 'bulk_import'),
('Geox', 'active', 'bulk_import'),
('Skechers', 'active', 'bulk_import'),
('Toms', 'active', 'bulk_import'),
('Allbirds', 'active', 'bulk_import'),
('Samsonite', 'active', 'bulk_import'),
('Tumi', 'active', 'bulk_import'),
('Rimowa', 'active', 'bulk_import'),
('Away', 'active', 'bulk_import'),
('Travelpro', 'active', 'bulk_import'),
('Delsey', 'active', 'bulk_import'),
('American Tourister', 'active', 'bulk_import'),
('Victorinox', 'active', 'bulk_import'),
('Briggs & Riley', 'active', 'bulk_import'),
('Eagle Creek', 'active', 'bulk_import'),
('Yeti Coolers', 'active', 'bulk_import'),
('Coleman', 'active', 'bulk_import'),
('Igloo', 'active', 'bulk_import'),
('Pelican', 'active', 'bulk_import'),
('RTIC Coolers', 'active', 'bulk_import'),
('Orca', 'active', 'bulk_import'),
('Engel', 'active', 'bulk_import'),
('Canyon', 'active', 'bulk_import'),
('Grizzly', 'active', 'bulk_import'),
('Bison', 'active', 'bulk_import'),
('Weber', 'active', 'bulk_import'),
('Traeger', 'active', 'bulk_import'),
('Big Green Egg', 'active', 'bulk_import'),
('Kamado Joe', 'active', 'bulk_import'),
('Char-Broil', 'active', 'bulk_import'),
('Napoleon', 'active', 'bulk_import'),
('Broil King', 'active', 'bulk_import'),
('Pit Boss', 'active', 'bulk_import'),
('Camp Chef', 'active', 'bulk_import'),
('Blackstone', 'active', 'bulk_import'),
('Le Creuset', 'active', 'bulk_import'),
('Staub', 'active', 'bulk_import'),
('Lodge', 'active', 'bulk_import'),
('All-Clad', 'active', 'bulk_import'),
('Calphalon', 'active', 'bulk_import'),
('Cuisinart Cookware', 'active', 'bulk_import'),
('T-fal', 'active', 'bulk_import'),
('Rachael Ray', 'active', 'bulk_import'),
('Pioneer Woman', 'active', 'bulk_import'),
('Caraway', 'active', 'bulk_import'),
('Vitamix', 'active', 'bulk_import'),
('Blendtec', 'active', 'bulk_import'),
('Ninja', 'active', 'bulk_import'),
('NutriBullet', 'active', 'bulk_import'),
('Magic Bullet', 'active', 'bulk_import'),
('Oster', 'active', 'bulk_import'),
('Hamilton Beach', 'active', 'bulk_import'),
('KitchenAid Blender', 'active', 'bulk_import'),
('Breville', 'active', 'bulk_import'),
('Cuisinart Blender', 'active', 'bulk_import'),
('Instant Pot', 'active', 'bulk_import'),
('Ninja Foodi', 'active', 'bulk_import'),
('Crock-Pot', 'active', 'bulk_import'),
('Pressure King Pro', 'active', 'bulk_import'),
('Mueller', 'active', 'bulk_import'),
('Cosori', 'active', 'bulk_import'),
('Mealthy', 'active', 'bulk_import'),
('Zavor', 'active', 'bulk_import'),
('Presto', 'active', 'bulk_import'),
('T-fal Pressure Cooker', 'active', 'bulk_import'),
('Nespresso', 'active', 'bulk_import'),
('Keurig', 'active', 'bulk_import'),
('Breville Coffee', 'active', 'bulk_import'),
('De''Longhi', 'active', 'bulk_import'),
('Cuisinart Coffee', 'active', 'bulk_import'),
('Mr. Coffee', 'active', 'bulk_import'),
('Hamilton Beach Coffee', 'active', 'bulk_import'),
('Ninja Coffee', 'active', 'bulk_import'),
('Technivorm', 'active', 'bulk_import'),
('Bonavita', 'active', 'bulk_import'),
('iRobot Roomba', 'active', 'bulk_import'),
('Eufy', 'active', 'bulk_import'),
('Roborock', 'active', 'bulk_import'),
('Ecovacs', 'active', 'bulk_import'),
('Neato', 'active', 'bulk_import'),
('Shark Robot', 'active', 'bulk_import'),
('Bissell Robot', 'active', 'bulk_import'),
('Xiaomi Robot', 'active', 'bulk_import'),
('Samsung Robot', 'active', 'bulk_import'),
('LG Robot', 'active', 'bulk_import'),
('Nest', 'active', 'bulk_import'),
('Ring', 'active', 'bulk_import'),
('Arlo', 'active', 'bulk_import'),
('Wyze', 'active', 'bulk_import'),
('Blink', 'active', 'bulk_import'),
('SimpliSafe', 'active', 'bulk_import'),
('ADT', 'active', 'bulk_import'),
('Vivint', 'active', 'bulk_import'),
('Lorex', 'active', 'bulk_import'),
('Reolink', 'active', 'bulk_import'),
('Philips Hue', 'active', 'bulk_import'),
('LIFX', 'active', 'bulk_import'),
('Nanoleaf', 'active', 'bulk_import'),
('Sengled', 'active', 'bulk_import'),
('TP-Link Kasa', 'active', 'bulk_import'),
('Wyze Bulb', 'active', 'bulk_import'),
('GE Lighting', 'active', 'bulk_import'),
('Sylvania', 'active', 'bulk_import'),
('Cree', 'active', 'bulk_import'),
('Feit Electric', 'active', 'bulk_import'),
('Anker', 'active', 'bulk_import'),
('RAVPower', 'active', 'bulk_import'),
('Aukey', 'active', 'bulk_import'),
('Belkin', 'active', 'bulk_import'),
('Mophie', 'active', 'bulk_import'),
('Jackery', 'active', 'bulk_import'),
('Goal Zero', 'active', 'bulk_import'),
('EcoFlow', 'active', 'bulk_import'),
('Bluetti', 'active', 'bulk_import'),
('Rockpals', 'active', 'bulk_import'),
('OtterBox', 'active', 'bulk_import'),
('Spigen', 'active', 'bulk_import'),
('Case-Mate', 'active', 'bulk_import'),
('Casetify', 'active', 'bulk_import'),
('UAG', 'active', 'bulk_import'),
('Lifeproof', 'active', 'bulk_import'),
('Tech21', 'active', 'bulk_import'),
('Ringke', 'active', 'bulk_import'),
('Supcase', 'active', 'bulk_import'),
('ESR', 'active', 'bulk_import'),
('PopSocket', 'active', 'bulk_import'),
('Spigen PopSocket', 'active', 'bulk_import'),
('Otter + Pop', 'active', 'bulk_import'),
('Casetify PopSocket', 'active', 'bulk_import'),
('Phone Loop', 'active', 'bulk_import'),
('Bunker Ring', 'active', 'bulk_import'),
('iRing', 'active', 'bulk_import'),
('Loopy', 'active', 'bulk_import'),
('Ohsnap', 'active', 'bulk_import'),
('Clckr', 'active', 'bulk_import'),
('Tile', 'active', 'bulk_import'),
('AirTag', 'active', 'bulk_import'),
('Samsung SmartTag', 'active', 'bulk_import'),
('Chipolo', 'active', 'bulk_import'),
('Orbit', 'active', 'bulk_import'),
('Nut', 'active', 'bulk_import'),
('TrackR', 'active', 'bulk_import'),
('Pebblebee', 'active', 'bulk_import'),
('Cube', 'active', 'bulk_import'),
('Whistle', 'active', 'bulk_import'),
('Sonos Speaker', 'active', 'bulk_import'),
('Bose Speaker', 'active', 'bulk_import'),
('JBL Speaker', 'active', 'bulk_import'),
('Ultimate Ears', 'active', 'bulk_import'),
('Marshall Speaker', 'active', 'bulk_import'),
('Bang & Olufsen Speaker', 'active', 'bulk_import'),
('Harman Kardon Speaker', 'active', 'bulk_import'),
('Beats Speaker', 'active', 'bulk_import'),
('Sony Speaker', 'active', 'bulk_import'),
('Anker Soundcore', 'active', 'bulk_import'),
('Amazon Echo', 'active', 'bulk_import'),
('Google Home', 'active', 'bulk_import'),
('Apple HomePod', 'active', 'bulk_import'),
('Sonos One', 'active', 'bulk_import'),
('Bose Home Speaker', 'active', 'bulk_import'),
('JBL Link', 'active', 'bulk_import'),
('Harman Kardon Invoke', 'active', 'bulk_import'),
('Facebook Portal', 'active', 'bulk_import'),
('Lenovo Smart Display', 'active', 'bulk_import'),
('LG XBOOM', 'active', 'bulk_import'),
('Roku', 'active', 'bulk_import'),
('Amazon Fire TV', 'active', 'bulk_import'),
('Apple TV', 'active', 'bulk_import'),
('Chromecast', 'active', 'bulk_import'),
('Nvidia Shield', 'active', 'bulk_import'),
('TiVo', 'active', 'bulk_import'),
('Sling TV', 'active', 'bulk_import'),
('Hulu', 'active', 'bulk_import'),
('YouTube TV', 'active', 'bulk_import'),
('Philo', 'active', 'bulk_import'),
('Peloton', 'active', 'bulk_import'),
('NordicTrack', 'active', 'bulk_import'),
('Bowflex', 'active', 'bulk_import'),
('Schwinn', 'active', 'bulk_import'),
('ProForm', 'active', 'bulk_import'),
('Echelon', 'active', 'bulk_import'),
('Sunny Health', 'active', 'bulk_import'),
('Keiser', 'active', 'bulk_import'),
('Concept2', 'active', 'bulk_import'),
('WaterRower', 'active', 'bulk_import'),
('Theragun', 'active', 'bulk_import'),
('Hyperice', 'active', 'bulk_import'),
('TimTam', 'active', 'bulk_import'),
('Ekrin', 'active', 'bulk_import'),
('Achedaway', 'active', 'bulk_import'),
('Vybe', 'active', 'bulk_import'),
('Opove', 'active', 'bulk_import'),
('Renpho', 'active', 'bulk_import'),
('LifePro', 'active', 'bulk_import'),
('Sportneer', 'active', 'bulk_import'),
('Manduka', 'active', 'bulk_import'),
('Lululemon Mat', 'active', 'bulk_import'),
('Jade Yoga', 'active', 'bulk_import'),
('Liforme', 'active', 'bulk_import'),
('Gaiam', 'active', 'bulk_import'),
('PrAna', 'active', 'bulk_import'),
('Alo Yoga Mat', 'active', 'bulk_import'),
('Yoloha', 'active', 'bulk_import'),
('Hugger Mugger', 'active', 'bulk_import'),
('Barefoot Yoga', 'active', 'bulk_import'),
('TRX', 'active', 'bulk_import'),
('Rogue Fitness', 'active', 'bulk_import'),
('Titan Fitness', 'active', 'bulk_import'),
('Rep Fitness', 'active', 'bulk_import'),
('CAP Barbell', 'active', 'bulk_import'),
('PowerBlock', 'active', 'bulk_import'),
('Bowflex Dumbbells', 'active', 'bulk_import'),
('NordicTrack Dumbbells', 'active', 'bulk_import'),
('Yes4All', 'active', 'bulk_import'),
('AmazonBasics Fitness', 'active', 'bulk_import'),
('Garmin Watch', 'active', 'bulk_import'),
('Fitbit Watch', 'active', 'bulk_import'),
('Apple Watch', 'active', 'bulk_import'),
('Samsung Galaxy Watch', 'active', 'bulk_import'),
('Fossil Smartwatch', 'active', 'bulk_import'),
('Suunto Watch', 'active', 'bulk_import'),
('Polar Watch', 'active', 'bulk_import'),
('Coros Watch', 'active', 'bulk_import'),
('Amazfit Watch', 'active', 'bulk_import'),
('Withings Watch', 'active', 'bulk_import'),
('Bose Headphones', 'active', 'bulk_import'),
('Sony Headphones', 'active', 'bulk_import'),
('Sennheiser Headphones', 'active', 'bulk_import'),
('Audio-Technica Headphones', 'active', 'bulk_import'),
('Beats Headphones', 'active', 'bulk_import'),
('JBL Headphones', 'active', 'bulk_import'),
('Skullcandy', 'active', 'bulk_import'),
('Jabra', 'active', 'bulk_import'),
('Plantronics', 'active', 'bulk_import'),
('Anker Soundcore Headphones', 'active', 'bulk_import'),
('AirPods', 'active', 'bulk_import'),
('Samsung Galaxy Buds', 'active', 'bulk_import'),
('Jabra Elite', 'active', 'bulk_import'),
('Sony WF', 'active', 'bulk_import'),
('Bose QuietComfort Earbuds', 'active', 'bulk_import'),
('Beats Fit Pro', 'active', 'bulk_import'),
('Sennheiser Momentum', 'active', 'bulk_import'),
('JBL Earbuds', 'active', 'bulk_import'),
('Anker Soundcore Earbuds', 'active', 'bulk_import'),
('Skullcandy Earbuds', 'active', 'bulk_import'),
('Kindle', 'active', 'bulk_import'),
('Kobo', 'active', 'bulk_import'),
('Nook', 'active', 'bulk_import'),
('Onyx Boox', 'active', 'bulk_import'),
('PocketBook', 'active', 'bulk_import'),
('Likebook', 'active', 'bulk_import'),
('Boyue', 'active', 'bulk_import'),
('Meebook', 'active', 'bulk_import'),
('Supernote', 'active', 'bulk_import'),
('reMarkable', 'active', 'bulk_import'),
('iPad', 'active', 'bulk_import'),
('Samsung Galaxy Tab', 'active', 'bulk_import'),
('Microsoft Surface', 'active', 'bulk_import'),
('Amazon Fire Tablet', 'active', 'bulk_import'),
('Lenovo Tab', 'active', 'bulk_import'),
('Huawei MatePad', 'active', 'bulk_import'),
('ASUS ZenPad', 'active', 'bulk_import'),
('LG G Pad', 'active', 'bulk_import'),
('Google Pixel Tablet', 'active', 'bulk_import'),
('Xiaomi Pad', 'active', 'bulk_import'),
('MacBook', 'active', 'bulk_import'),
('Dell XPS', 'active', 'bulk_import'),
('HP Spectre', 'active', 'bulk_import'),
('Lenovo ThinkPad', 'active', 'bulk_import'),
('ASUS ZenBook', 'active', 'bulk_import'),
('Microsoft Surface Laptop', 'active', 'bulk_import'),
('Acer Swift', 'active', 'bulk_import'),
('LG Gram', 'active', 'bulk_import'),
('Razer Blade', 'active', 'bulk_import'),
('MSI Prestige', 'active', 'bulk_import'),
('iPhone', 'active', 'bulk_import'),
('Samsung Galaxy', 'active', 'bulk_import'),
('Google Pixel', 'active', 'bulk_import'),
('OnePlus Phone', 'active', 'bulk_import'),
('Xiaomi Phone', 'active', 'bulk_import'),
('Oppo Phone', 'active', 'bulk_import'),
('Vivo Phone', 'active', 'bulk_import'),
('Huawei Phone', 'active', 'bulk_import'),
('Motorola Phone', 'active', 'bulk_import'),
('Nokia Phone', 'active', 'bulk_import'),
('Tesla', 'active', 'bulk_import'),
('BMW', 'active', 'bulk_import'),
('Mercedes-Benz', 'active', 'bulk_import'),
('Audi', 'active', 'bulk_import'),
('Porsche', 'active', 'bulk_import'),
('Lexus', 'active', 'bulk_import'),
('Acura', 'active', 'bulk_import'),
('Infiniti', 'active', 'bulk_import'),
('Cadillac', 'active', 'bulk_import'),
('Lincoln', 'active', 'bulk_import'),
('Yeti Rambler', 'active', 'bulk_import'),
('Hydro Flask Bottle', 'active', 'bulk_import'),
('S''well Bottle', 'active', 'bulk_import'),
('Contigo Bottle', 'active', 'bulk_import'),
('CamelBak Bottle', 'active', 'bulk_import'),
('Klean Kanteen Bottle', 'active', 'bulk_import'),
('Thermos Bottle', 'active', 'bulk_import'),
('Stanley Bottle', 'active', 'bulk_import'),
('RTIC Bottle', 'active', 'bulk_import'),
('Nalgene Bottle', 'active', 'bulk_import'),
('Patagonia Jacket', 'active', 'bulk_import'),
('The North Face Jacket', 'active', 'bulk_import'),
('Arc''teryx Jacket', 'active', 'bulk_import'),
('Canada Goose', 'active', 'bulk_import'),
('Moncler', 'active', 'bulk_import'),
('Columbia Jacket', 'active', 'bulk_import'),
('Mammut Jacket', 'active', 'bulk_import'),
('Mountain Hardwear', 'active', 'bulk_import'),
('Outdoor Research', 'active', 'bulk_import'),
('Rab', 'active', 'bulk_import'),
('Osprey', 'active', 'bulk_import'),
('Deuter', 'active', 'bulk_import'),
('Gregory', 'active', 'bulk_import'),
('Kelty', 'active', 'bulk_import'),
('REI Co-op', 'active', 'bulk_import'),
('Patagonia Backpack', 'active', 'bulk_import'),
('The North Face Backpack', 'active', 'bulk_import'),
('Arc''teryx Backpack', 'active', 'bulk_import'),
('Fjällräven', 'active', 'bulk_import'),
('Herschel', 'active', 'bulk_import'),
('GoPro Hero', 'active', 'bulk_import'),
('DJI Osmo', 'active', 'bulk_import'),
('Insta360', 'active', 'bulk_import'),
('Sony Action Cam', 'active', 'bulk_import'),
('Akaso', 'active', 'bulk_import'),
('Apeman', 'active', 'bulk_import'),
('Campark', 'active', 'bulk_import'),
('SJCAM', 'active', 'bulk_import'),
('YI Action', 'active', 'bulk_import'),
('Garmin VIRB', 'active', 'bulk_import'),
('Bose SoundLink', 'active', 'bulk_import'),
('JBL Flip', 'active', 'bulk_import'),
('Ultimate Ears Boom', 'active', 'bulk_import'),
('Sony SRS', 'active', 'bulk_import'),
('Anker Soundcore Motion', 'active', 'bulk_import'),
('Marshall Emberton', 'active', 'bulk_import'),
('Bang & Olufsen Beosound', 'active', 'bulk_import'),
('Harman Kardon Onyx', 'active', 'bulk_import'),
('Beats Pill', 'active', 'bulk_import'),
('Tribit', 'active', 'bulk_import'),
('Roku Streaming Stick', 'active', 'bulk_import'),
('Amazon Fire Stick', 'active', 'bulk_import'),
('Chromecast', 'active', 'bulk_import'),
('Apple TV 4K', 'active', 'bulk_import'),
('Nvidia Shield TV', 'active', 'bulk_import'),
('Xiaomi Mi Box', 'active', 'bulk_import'),
('TiVo Stream', 'active', 'bulk_import'),
('Roku Ultra', 'active', 'bulk_import'),
('Amazon Fire Cube', 'active', 'bulk_import'),
('Google Chromecast Ultra', 'active', 'bulk_import'),
('Ring Doorbell', 'active', 'bulk_import'),
('Nest Doorbell', 'active', 'bulk_import'),
('Arlo Doorbell', 'active', 'bulk_import'),
('Eufy Doorbell', 'active', 'bulk_import'),
('Wyze Doorbell', 'active', 'bulk_import'),
('Blink Doorbell', 'active', 'bulk_import'),
('SimpliSafe Doorbell', 'active', 'bulk_import'),
('Reolink Doorbell', 'active', 'bulk_import'),
('Amcrest Doorbell', 'active', 'bulk_import'),
('RemoBell', 'active', 'bulk_import'),
('Philips Sonicare', 'active', 'bulk_import'),
('Oral-B', 'active', 'bulk_import'),
('Waterpik', 'active', 'bulk_import'),
('Quip', 'active', 'bulk_import'),
('Burst', 'active', 'bulk_import'),
('Goby', 'active', 'bulk_import'),
('Foreo', 'active', 'bulk_import'),
('Fairywill', 'active', 'bulk_import'),
('AquaSonic', 'active', 'bulk_import'),
('Liberex', 'active', 'bulk_import'),
('Dyson Airwrap', 'active', 'bulk_import'),
('Revlon One-Step', 'active', 'bulk_import'),
('T3 Micro', 'active', 'bulk_import'),
('GHD', 'active', 'bulk_import'),
('BaBylissPRO', 'active', 'bulk_import'),
('Hot Tools', 'active', 'bulk_import'),
('Conair', 'active', 'bulk_import'),
('Remington', 'active', 'bulk_import'),
('Drybar', 'active', 'bulk_import'),
('Bio Ionic', 'active', 'bulk_import'),
('Clarisonic', 'active', 'bulk_import'),
('Foreo Luna', 'active', 'bulk_import'),
('PMD', 'active', 'bulk_import'),
('NuFace', 'active', 'bulk_import'),
('Tria Beauty', 'active', 'bulk_import'),
('Silk''n', 'active', 'bulk_import'),
('Trophy Skin', 'active', 'bulk_import'),
('Dr. Dennis Gross', 'active', 'bulk_import'),
('LightStim', 'active', 'bulk_import'),
('CurrentBody', 'active', 'bulk_import'),
('Therabody', 'active', 'bulk_import'),
('Hyperice Hypervolt', 'active', 'bulk_import'),
('Ekrin Athletics', 'active', 'bulk_import'),
('TimTam Power Massager', 'active', 'bulk_import'),
('Achedaway Pro', 'active', 'bulk_import'),
('Vybe Pro', 'active', 'bulk_import'),
('Opove M3 Pro', 'active', 'bulk_import'),
('Renpho Massage Gun', 'active', 'bulk_import'),
('LifePro Sonic', 'active', 'bulk_import'),
('Sportneer Elite', 'active', 'bulk_import'),
('Manduka PRO', 'active', 'bulk_import'),
('Lululemon Reversible Mat', 'active', 'bulk_import'),
('Jade Harmony', 'active', 'bulk_import'),
('Liforme Yoga Mat', 'active', 'bulk_import'),
('Gaiam Premium', 'active', 'bulk_import'),
('PrAna E.C.O.', 'active', 'bulk_import'),
('Alo Warrior Mat', 'active', 'bulk_import'),
('Yoloha Cork', 'active', 'bulk_import'),
('Hugger Mugger Para Rubber', 'active', 'bulk_import'),
('Barefoot Yoga Extra Thick', 'active', 'bulk_import'),
('TRX Home2', 'active', 'bulk_import'),
('Rogue Echo Bike', 'active', 'bulk_import'),
('Titan Fitness T-3', 'active', 'bulk_import'),
('Rep Fitness PR-4000', 'active', 'bulk_import'),
('CAP Barbell Olympic', 'active', 'bulk_import'),
('PowerBlock Elite', 'active', 'bulk_import'),
('Bowflex SelectTech', 'active', 'bulk_import'),
('NordicTrack Adjustable', 'active', 'bulk_import'),
('Yes4All Dumbbells', 'active', 'bulk_import'),
('AmazonBasics Neoprene', 'active', 'bulk_import'),
('Garmin Fenix', 'active', 'bulk_import'),
('Fitbit Sense', 'active', 'bulk_import'),
('Apple Watch Ultra', 'active', 'bulk_import'),
('Samsung Galaxy Watch 5', 'active', 'bulk_import'),
('Fossil Gen 6', 'active', 'bulk_import'),
('Suunto 9', 'active', 'bulk_import'),
('Polar Vantage', 'active', 'bulk_import'),
('Coros Apex', 'active', 'bulk_import'),
('Amazfit GTR', 'active', 'bulk_import'),
('Withings ScanWatch', 'active', 'bulk_import'),
('Bose QuietComfort', 'active', 'bulk_import'),
('Sony WH-1000XM5', 'active', 'bulk_import'),
('Sennheiser Momentum 4', 'active', 'bulk_import'),
('Audio-Technica ATH-M50x', 'active', 'bulk_import'),
('Beats Studio3', 'active', 'bulk_import'),
('JBL Live', 'active', 'bulk_import'),
('Skullcandy Crusher', 'active', 'bulk_import'),
('Jabra Elite 85h', 'active', 'bulk_import'),
('Plantronics BackBeat', 'active', 'bulk_import'),
('Anker Soundcore Life', 'active', 'bulk_import'),
('AirPods Pro', 'active', 'bulk_import'),
('Samsung Galaxy Buds Pro', 'active', 'bulk_import'),
('Jabra Elite 85t', 'active', 'bulk_import'),
('Sony WF-1000XM4', 'active', 'bulk_import'),
('Bose QuietComfort Earbuds II', 'active', 'bulk_import'),
('Beats Fit Pro', 'active', 'bulk_import'),
('Sennheiser Momentum True Wireless', 'active', 'bulk_import'),
('JBL Tour Pro', 'active', 'bulk_import'),
('Anker Soundcore Liberty', 'active', 'bulk_import'),
('Skullcandy Indy', 'active', 'bulk_import'),
('Kindle Paperwhite', 'active', 'bulk_import'),
('Kobo Clara', 'active', 'bulk_import'),
('Nook GlowLight', 'active', 'bulk_import'),
('Onyx Boox Nova', 'active', 'bulk_import'),
('PocketBook Touch', 'active', 'bulk_import'),
('Likebook Mars', 'active', 'bulk_import'),
('Boyue Likebook', 'active', 'bulk_import'),
('Meebook P78', 'active', 'bulk_import'),
('Supernote A5', 'active', 'bulk_import'),
('reMarkable 2', 'active', 'bulk_import'),
('iPad Pro', 'active', 'bulk_import'),
('Samsung Galaxy Tab S8', 'active', 'bulk_import'),
('Microsoft Surface Pro', 'active', 'bulk_import'),
('Amazon Fire HD', 'active', 'bulk_import'),
('Lenovo Tab P11', 'active', 'bulk_import'),
('Huawei MatePad Pro', 'active', 'bulk_import'),
('ASUS ZenPad 3S', 'active', 'bulk_import'),
('LG G Pad 5', 'active', 'bulk_import'),
('Google Pixel Slate', 'active', 'bulk_import'),
('Xiaomi Pad 5', 'active', 'bulk_import'),
('MacBook Pro', 'active', 'bulk_import'),
('Dell XPS 13', 'active', 'bulk_import'),
('HP Spectre x360', 'active', 'bulk_import'),
('Lenovo ThinkPad X1', 'active', 'bulk_import'),
('ASUS ZenBook 14', 'active', 'bulk_import'),
('Microsoft Surface Laptop 4', 'active', 'bulk_import'),
('Acer Swift 3', 'active', 'bulk_import'),
('LG Gram 17', 'active', 'bulk_import'),
('Razer Blade 15', 'active', 'bulk_import'),
('MSI Prestige 14', 'active', 'bulk_import'),
('iPhone 14', 'active', 'bulk_import'),
('Samsung Galaxy S23', 'active', 'bulk_import'),
('Google Pixel 7', 'active', 'bulk_import'),
('OnePlus 11', 'active', 'bulk_import'),
('Xiaomi 13', 'active', 'bulk_import'),
('Oppo Find X5', 'active', 'bulk_import'),
('Vivo X90', 'active', 'bulk_import'),
('Huawei P60', 'active', 'bulk_import'),
('Motorola Edge', 'active', 'bulk_import'),
('Nokia G50', 'active', 'bulk_import'),
('Shein', 'active', 'bulk_import'),
('Temu', 'active', 'bulk_import'),
('AliExpress', 'active', 'bulk_import'),
('Wish', 'active', 'bulk_import'),
('DHgate', 'active', 'bulk_import'),
('Banggood', 'active', 'bulk_import'),
('Gearbest', 'active', 'bulk_import'),
('Romwe', 'active', 'bulk_import'),
('Zaful', 'active', 'bulk_import'),
('Rosegal', 'active', 'bulk_import'),
('Supreme', 'active', 'bulk_import'),
('Off-White', 'active', 'bulk_import'),
('Bape', 'active', 'bulk_import'),
('Stussy', 'active', 'bulk_import'),
('Palace', 'active', 'bulk_import'),
('Kith', 'active', 'bulk_import'),
('Anti Social Social Club', 'active', 'bulk_import'),
('Fear of God', 'active', 'bulk_import'),
('Yeezy', 'active', 'bulk_import'),
('Jordan Brand', 'active', 'bulk_import'),
('Crocs Classic', 'active', 'bulk_import'),
('Birkenstock Arizona', 'active', 'bulk_import'),
('UGG Classic', 'active', 'bulk_import'),
('Dr. Martens 1460', 'active', 'bulk_import'),
('Clarks Desert Boot', 'active', 'bulk_import'),
('Ecco Soft 7', 'active', 'bulk_import'),
('Geox Respira', 'active', 'bulk_import'),
('Skechers Go Walk', 'active', 'bulk_import'),
('Toms Alpargata', 'active', 'bulk_import'),
('Allbirds Tree Runners', 'active', 'bulk_import'),
('Samsonite Winfield', 'active', 'bulk_import'),
('Tumi Alpha', 'active', 'bulk_import'),
('Rimowa Original', 'active', 'bulk_import'),
('Away Bigger Carry-On', 'active', 'bulk_import'),
('Travelpro Platinum Elite', 'active', 'bulk_import'),
('Delsey Chatelet', 'active', 'bulk_import'),
('American Tourister Moonlight', 'active', 'bulk_import'),
('Victorinox Spectra', 'active', 'bulk_import'),
('Briggs & Riley Baseline', 'active', 'bulk_import'),
('Eagle Creek Expanse', 'active', 'bulk_import'),
('Yeti Tundra', 'active', 'bulk_import'),
('Coleman Xtreme', 'active', 'bulk_import'),
('Igloo MaxCold', 'active', 'bulk_import'),
('Pelican Elite', 'active', 'bulk_import'),
('RTIC 65', 'active', 'bulk_import'),
('Orca 58', 'active', 'bulk_import'),
('Engel DeepBlue', 'active', 'bulk_import'),
('Canyon Outfitter', 'active', 'bulk_import'),
('Grizzly 60', 'active', 'bulk_import'),
('Bison 75', 'active', 'bulk_import'),
('Weber Genesis', 'active', 'bulk_import'),
('Traeger Pro', 'active', 'bulk_import'),
('Big Green Egg Large', 'active', 'bulk_import'),
('Kamado Joe Classic', 'active', 'bulk_import'),
('Char-Broil Performance', 'active', 'bulk_import'),
('Napoleon Prestige', 'active', 'bulk_import'),
('Broil King Regal', 'active', 'bulk_import'),
('Pit Boss Austin XL', 'active', 'bulk_import'),
('Camp Chef SmokePro', 'active', 'bulk_import'),
('Blackstone 36', 'active', 'bulk_import'),
('Le Creuset Dutch Oven', 'active', 'bulk_import'),
('Staub Cocotte', 'active', 'bulk_import'),
('Lodge Cast Iron', 'active', 'bulk_import'),
('All-Clad D3', 'active', 'bulk_import'),
('Calphalon Contemporary', 'active', 'bulk_import'),
('Cuisinart MultiClad', 'active', 'bulk_import'),
('T-fal Ultimate', 'active', 'bulk_import'),
('Rachael Ray Cucina', 'active', 'bulk_import'),
('Pioneer Woman Timeless', 'active', 'bulk_import'),
('Caraway Cookware Set', 'active', 'bulk_import'),
('Vitamix 5200', 'active', 'bulk_import'),
('Blendtec Designer', 'active', 'bulk_import'),
('Ninja Professional', 'active', 'bulk_import'),
('NutriBullet Pro', 'active', 'bulk_import'),
('Magic Bullet Blender', 'active', 'bulk_import'),
('Oster Versa', 'active', 'bulk_import'),
('Hamilton Beach Power Elite', 'active', 'bulk_import'),
('KitchenAid K400', 'active', 'bulk_import'),
('Breville Super Q', 'active', 'bulk_import'),
('Cuisinart Hurricane', 'active', 'bulk_import'),
('Instant Pot Duo', 'active', 'bulk_import'),
('Ninja Foodi Deluxe', 'active', 'bulk_import'),
('Crock-Pot Express', 'active', 'bulk_import'),
('Pressure King Pro 20-in-1', 'active', 'bulk_import'),
('Mueller UltraPot', 'active', 'bulk_import'),
('Cosori Premium', 'active', 'bulk_import'),
('Mealthy MultiPot', 'active', 'bulk_import'),
('Zavor LUX', 'active', 'bulk_import'),
('Presto Precise', 'active', 'bulk_import'),
('T-fal CY505', 'active', 'bulk_import'),
('Nespresso VertuoPlus', 'active', 'bulk_import'),
('Keurig K-Elite', 'active', 'bulk_import'),
('Breville Barista Express', 'active', 'bulk_import'),
('De''Longhi Magnifica', 'active', 'bulk_import'),
('Cuisinart DCC-3200', 'active', 'bulk_import'),
('Mr. Coffee Optimal Brew', 'active', 'bulk_import'),
('Hamilton Beach FlexBrew', 'active', 'bulk_import'),
('Ninja Specialty', 'active', 'bulk_import'),
('Technivorm Moccamaster', 'active', 'bulk_import'),
('Bonavita Connoisseur', 'active', 'bulk_import'),
('iRobot Roomba j7', 'active', 'bulk_import'),
('Eufy RoboVac', 'active', 'bulk_import'),
('Roborock S7', 'active', 'bulk_import'),
('Ecovacs Deebot', 'active', 'bulk_import'),
('Neato D8', 'active', 'bulk_import'),
('Shark IQ Robot', 'active', 'bulk_import'),
('Bissell SpinWave', 'active', 'bulk_import'),
('Xiaomi Mi Robot', 'active', 'bulk_import'),
('Samsung Jet Bot', 'active', 'bulk_import'),
('LG CordZero', 'active', 'bulk_import'),
('Nest Learning Thermostat', 'active', 'bulk_import'),
('Ring Video Doorbell', 'active', 'bulk_import'),
('Arlo Pro 4', 'active', 'bulk_import'),
('Wyze Cam v3', 'active', 'bulk_import'),
('Blink Outdoor', 'active', 'bulk_import'),
('SimpliSafe SS3', 'active', 'bulk_import'),
('ADT Command', 'active', 'bulk_import'),
('Vivint Smart Home', 'active', 'bulk_import'),
('Lorex 4K', 'active', 'bulk_import'),
('Reolink Argus', 'active', 'bulk_import'),
('Philips Hue White', 'active', 'bulk_import'),
('LIFX A19', 'active', 'bulk_import'),
('Nanoleaf Shapes', 'active', 'bulk_import'),
('Sengled Smart LED', 'active', 'bulk_import'),
('TP-Link Kasa Smart', 'active', 'bulk_import'),
('Wyze Bulb Color', 'active', 'bulk_import'),
('GE Cync', 'active', 'bulk_import'),
('Sylvania Smart+', 'active', 'bulk_import'),
('Cree Connected', 'active', 'bulk_import'),
('Feit Electric Smart', 'active', 'bulk_import'),
('Anker PowerCore', 'active', 'bulk_import'),
('RAVPower Portable', 'active', 'bulk_import'),
('Aukey Power Bank', 'active', 'bulk_import'),
('Belkin Boost Charge', 'active', 'bulk_import'),
('Mophie Powerstation', 'active', 'bulk_import'),
('Jackery Explorer', 'active', 'bulk_import'),
('Goal Zero Yeti', 'active', 'bulk_import'),
('EcoFlow River', 'active', 'bulk_import'),
('Bluetti AC200', 'active', 'bulk_import'),
('Rockpals 300W', 'active', 'bulk_import')
ON CONFLICT (brand_name) DO NOTHING;